"""empty message

Revision ID: fb7708154dd8
Revises: 37cad7d77bb4
Create Date: 2026-06-16 23:52:53.963853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb7708154dd8'
down_revision: Union[str, Sequence[str], None] = '37cad7d77bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_constraint(op.f('forms_button_id_key'), 'forms', type_='unique')
    op.add_column('users', sa.Column('group', sa.String(length=10), nullable=True))
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=False)
    op.drop_column('users', 'group')
    op.create_unique_constraint(op.f('forms_button_id_key'), 'forms', ['button_id'], postgresql_nulls_not_distinct=False)
    op.create_table('profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('profiles_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    # ### end Alembic commands ###
